repos = [
    "dhth/act3-runner",
    "dhth/act3",
    "dhth/agent0",
    "dhth/agent1",
    "dhth/atls",
    "dhth/bmm",
    "dhth/chronotes",
    "dhth/commits",
    "dhth/cueitup",
    "dhth/ddiff",
    "dhth/dfft",
    "dhth/dstll",
    "dhth/ecscope",
    "dhth/ecsv",
    "dhth/envee",
    "dhth/ghx",
    "dhth/grafq",
    "dhth/graphc",
    "dhth/hours",
    "dhth/kplay",
    "dhth/mrj-runner",
    "dhth/mrj",
    "dhth/mult",
    "dhth/omm",
    "dhth/outtasync",
    "dhth/prs",
    "dhth/punchout",
    "dhth/schemas",
    "dhth/shfl",
    "dhth/squidge",
    "dhth/squish",
    "dhth/swatches",
    "dhth/tash",
    "dhth/tbll",
    "dhth/tflens",
    "dhth/ting",
    "dhth/tomo",
    "dhth/unreleased-report",
    "dhth/unreleased",
    "dhth/urll",
    "dhth/zero2prod",
]
trusted_authors = ["dependabot[bot]", "github-actions[bot]"]
base_branch = "main"
merge_if_blocked = false
merge_if_checks_skipped = true
merge_type = "squash"
